name: release
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Loging to GitHub Docker Registry
        run: |
          echo ${{ secrets.GITHUB_PACKAGE_TOKEN }} | docker login -u danielpacak --password-stdin docker.pkg.github.com
      - name: Release
        uses: goreleaser/goreleaser-action@v1
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_PACKAGE_TOKEN }}
