name: build
on:
  push:
    tags:
      - "*"
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Golang
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Check out code
        uses: actions/checkout@v1
      - name: Build
        run: make
      - name: Release
        run: curl -sL https://git.io/goreleaser | bash -s -- --rm-dist
